SET SERVEROUTPUT ON;

BEGIN 
	FOR REC IN (SELECT ETD,ENAME,DEPTNO,DEPTNAME,GENDER,AGE,BASICAL FROM EMP 
				WHERE GENDER ='M' AND DEPTNO='HR')
		LOOP
			DBMS_OUTPUT.PUT_LINE('EID :'||REC.EID);
			DBMS_OUTPUT.PUT_LINE('ENAME :'||REC.ENAME);
			DBMS_OUTPUT.PUT_LINE('DEPTNO :'||REC.DEPTNO);
			DBMS_OUTPUT.PUT_LINE('DNAME :'||REC.DEPTNAME);
			DBMS_OUTPUT.PUT_LINE('GENDER :'||REC.GENDER);
			DBMS_OUTPUT.PUT_LINE('AGES :'||REC.AGE);
			DBMS_OUTPUT.PUT_LINE('BASICAL :'||REC.BASICAL);
			END LOOP;
END;
/
	